# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: 'b4242eb1-5e7e-4948-ab48-97b52f612d0e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevOpsExpert-Dev1'
    location: 'Central US'
    templateLocation: 'URL of the file'
    overrideParameters: 'projectName cicd'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelinetemplate'
  displayName: 'Run a multi-line script'
